### ISSUE TITLE
Include Pokémon type advantage

### ISSUE THREAD

**Issue by 11michalis11** [11michalis11/pykemon_battle#5]
Include a constant matrix (or dictionary) that has the type effectiveness between moves and pokemon

**Comment by geraintpalmer** [comment]
And STAB (same type attack bonus) - a fire type pokemon using a fire type move deals 50% more damage.

**Comment by 11michalis11** [comment]
@geraintpalmer Yeah this issue should have been closed. I did include STAB as well.

This is the blog that I based the damage formula on: [battle damage](https://www.math.miami.edu/~jam/azure/compendium/battdam.htm)
